### ISSUE TITLE
`headers.get` is not a function when deploying to Vercel

### ISSUE THREAD

**Issue by gdomaradzki** [sergiodxa/remix-i18next#117]
### Describe the bug

When deploying a Remix application with `remix-i18next` to Vercel, the app will crash immediately with the following error:

```
2023-02-16T03:41:56.394Z    cd325fbc-7def-4990-83fd-b0d5a7fe6d3a    ERROR    Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: headers.get is not a function","reason":{"errorType":"TypeError","errorMessage":"headers.get is not a function","stack":["TypeError: headers.get is not a function","    at getClientLocales (/var/task/node_modules/remix-i18next/build/lib/get-client-locales.js:7:34)","    at LanguageDetector.fromHeader (/var/task/node_modules/remix-i18next/build/server.js:163:65)","    at LanguageDetector.detect (/var/task/node_modules/remix-i18next/build/server.js:129:37)","    at processTicksAndRejections (node:internal/process/task_queues:95:5)","    at initTranslate (/var/task/build/index.js:500:64)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: headers.get is not a function","    at process.<anonymous> (file:///var/runtime/index.mjs:1194:17)","    at process.emit (node:events:525:35)","    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

After investigating and testing things out, it seems the `requestOrHeaders` ignores the `if` statement in the `getHeaders` function, but it's still of Request type.

By changing the function to this (by inverting the logic) I was able to deploy to Vercel and not errors happening so far:

```
function getHeaders(requestOrHeaders: Request | Headers): Headers {
  if (requestOrHeaders instanceof Headers) {
    return requestOrHeaders;
  }

  return requestOrHeaders.headers;
}
```

### Your Example Website or App

https://github.com/gdomaradzki/test-vercel

### Steps to Reproduce the Bug or Issue

1. Clone the example project or create a new Remix project following `remix-i18next` README
2. Try to deploy to Vercel

### Expected behavior

As a user I expected the app to work correctly on deploy, but the got internal errors

### Platform

- OS: Windows
- Browser: Chrome

**Comment by JulienHe** [comment]
I'm getting the exact same error on a project I deploy recently :/

**Comment by pbilyk** [comment]
I rolled the Vercel CLI version back for now, and the issue got fixed.

**Comment by ErlanBelekov** [comment]
also running into this, how can I set a previous vercel cli version from the dashboard? @pbilyk

**Comment by ErlanBelekov** [comment]
Hi @sergiodxa , please check out the PR https://github.com/sergiodxa/remix-i18next/pull/118
it should fix this issue, I copied the solution of @gdomaradzki into a PR

**Comment by pbilyk** [comment]
@ErlanBelekov You can do this by adding an environment variable `VERCEL_CLI_VERSION = vercel@28.15.3`.

It's also being looked at on vercel side here: https://github.com/orgs/vercel/discussions/1547
